@startuml

skinparam rectangle<<behavior>> {
	roundCorner 25
}
sprite $component jar:archimate/component

package Omnius.Axus.Ui.Desktop {
    package Omnius.Axus.Ui.Desktop.Presenters {
        rectangle UserProfileFinder <<$component>><<behavior>>
        rectangle UserProfileUploader <<$component>><<behavior>>
        rectangle FileFinder <<$component>><<behavior>>
        rectangle FileDowndoader <<$component>><<behavior>>
        rectangle FileUploader <<$component>><<behavior>>
    }
}

package Omnius.Axus.Interactors {
    rectangle FilePublisher <<$component>><<behavior>>
    rectangle FileSubscriber <<$component>><<behavior>>
    rectangle UserProfilePublisher <<$component>><<behavior>>
    rectangle UserProfileSubscriber <<$component>><<behavior>>
}

package Omnius.Axus.Daemon {
    rectangle AxusService.Client <<$component>><<behavior>>
    rectangle AxusService.Server <<$component>><<behavior>>
}

package Omnius.Axus.Daemon {
    rectangle AxusServiceImpl <<$component>><<behavior>>
}

package Ominus.Axus.Engines {
    package Ominus.Axus.Engines.Connectors {
        rectangle TcpConnector <<$component>><<behavior>>
    }
    package Ominus.Axus.Engines.Exchangers {
        rectangle ContentExchanger <<$component>><<behavior>>
        rectangle DeclaredMessageExchanger <<$component>><<behavior>>
    }
    package Ominus.Axus.Engines.Mediators {
        rectangle CkadMediator <<$component>><<behavior>>
    }
    package Ominus.Axus.Engines.Storages {
        rectangle PublishedFileStorage <<$component>><<behavior>>
        rectangle SubscribedFileStorage <<$component>><<behavior>>
        rectangle PublishedDeclaredMessage <<$component>><<behavior>>
        rectangle SubscribedDeclaredMessage <<$component>><<behavior>>
    }
}

UserProfileFinder -down-> UserProfileSubscriber
UserProfileUploader -down-> UserProfilePublisher
FileFinder -down-> UserProfileFinder
FileDowndoader -down-> FileSubscriber
FileUploader -down-> FilePublisher

FilePublisher -down-> AxusService.Client
FileSubscriber -down-> AxusService.Client
UserProfilePublisher -down-> AxusService.Client
UserProfileSubscriber -down-> AxusService.Client

AxusService.Client .down.> AxusService.Server : TCP

AxusService.Server -down-> AxusServiceImpl

AxusServiceImpl -down-> Ominus.Axus.Engines

CkadMediator -left-> TcpConnector

ContentExchanger -up-> TcpConnector
ContentExchanger -up-> CkadMediator
ContentExchanger -down-> PublishedFileStorage
ContentExchanger -down-> SubscribedFileStorage

DeclaredMessageExchanger -up-> TcpConnector
DeclaredMessageExchanger -up-> CkadMediator
DeclaredMessageExchanger -down-> PublishedDeclaredMessage
DeclaredMessageExchanger -down-> SubscribedDeclaredMessage

@enduml
