// <auto-generated/>
#nullable enable

namespace Omnius.Xeus.Interactors.Internal.Models
{
    public sealed partial class DownloadingUserProfileItem : global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem>
    {
        public static global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem> Formatter => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem>.Formatter;
        public static global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem Empty => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem>.Empty;

        static DownloadingUserProfileItem()
        {
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem>.Formatter = new ___CustomFormatter();
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem>.Empty = new global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem(global::Omnius.Core.Cryptography.OmniSignature.Empty, global::Omnius.Core.Cryptography.OmniHash.Empty, global::Omnius.Core.RocketPack.Timestamp.Zero);
        }

        private readonly global::System.Lazy<int> ___hashCode;

        public DownloadingUserProfileItem(global::Omnius.Core.Cryptography.OmniSignature signature, global::Omnius.Core.Cryptography.OmniHash contentHash, global::Omnius.Core.RocketPack.Timestamp creationTime)
        {
            if (signature is null) throw new global::System.ArgumentNullException("signature");
            this.Signature = signature;
            this.ContentHash = contentHash;
            this.CreationTime = creationTime;

            ___hashCode = new global::System.Lazy<int>(() =>
            {
                var ___h = new global::System.HashCode();
                if (signature != default) ___h.Add(signature.GetHashCode());
                if (contentHash != default) ___h.Add(contentHash.GetHashCode());
                if (creationTime != default) ___h.Add(creationTime.GetHashCode());
                return ___h.ToHashCode();
            });
        }

        public global::Omnius.Core.Cryptography.OmniSignature Signature { get; }
        public global::Omnius.Core.Cryptography.OmniHash ContentHash { get; }
        public global::Omnius.Core.RocketPack.Timestamp CreationTime { get; }

        public static global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem Import(global::System.Buffers.ReadOnlySequence<byte> sequence, global::Omnius.Core.IBytesPool bytesPool)
        {
            var reader = new global::Omnius.Core.RocketPack.RocketPackObjectReader(sequence, bytesPool);
            return Formatter.Deserialize(ref reader, 0);
        }
        public void Export(global::System.Buffers.IBufferWriter<byte> bufferWriter, global::Omnius.Core.IBytesPool bytesPool)
        {
            var writer = new global::Omnius.Core.RocketPack.RocketPackObjectWriter(bufferWriter, bytesPool);
            Formatter.Serialize(ref writer, this, 0);
        }

        public static bool operator ==(global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem? left, global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem? right)
        {
            return (right is null) ? (left is null) : right.Equals(left);
        }
        public static bool operator !=(global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem? left, global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem? right)
        {
            return !(left == right);
        }
        public override bool Equals(object? other)
        {
            if (other is not global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem) return false;
            return this.Equals((global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem)other);
        }
        public bool Equals(global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem? target)
        {
            if (target is null) return false;
            if (object.ReferenceEquals(this, target)) return true;
            if (this.Signature != target.Signature) return false;
            if (this.ContentHash != target.ContentHash) return false;
            if (this.CreationTime != target.CreationTime) return false;

            return true;
        }
        public override int GetHashCode() => ___hashCode.Value;

        private sealed class ___CustomFormatter : global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem>
        {
            public void Serialize(ref global::Omnius.Core.RocketPack.RocketPackObjectWriter w, in global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem value, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                if (value.Signature != global::Omnius.Core.Cryptography.OmniSignature.Empty)
                {
                    w.Write((uint)1);
                    global::Omnius.Core.Cryptography.OmniSignature.Formatter.Serialize(ref w, value.Signature, rank + 1);
                }
                if (value.ContentHash != global::Omnius.Core.Cryptography.OmniHash.Empty)
                {
                    w.Write((uint)2);
                    global::Omnius.Core.Cryptography.OmniHash.Formatter.Serialize(ref w, value.ContentHash, rank + 1);
                }
                if (value.CreationTime != global::Omnius.Core.RocketPack.Timestamp.Zero)
                {
                    w.Write((uint)3);
                    w.Write(value.CreationTime);
                }
                w.Write((uint)0);
            }
            public global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem Deserialize(ref global::Omnius.Core.RocketPack.RocketPackObjectReader r, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                global::Omnius.Core.Cryptography.OmniSignature p_signature = global::Omnius.Core.Cryptography.OmniSignature.Empty;
                global::Omnius.Core.Cryptography.OmniHash p_contentHash = global::Omnius.Core.Cryptography.OmniHash.Empty;
                global::Omnius.Core.RocketPack.Timestamp p_creationTime = global::Omnius.Core.RocketPack.Timestamp.Zero;

                for (; ; )
                {
                    uint id = r.GetUInt32();
                    if (id == 0) break;
                    switch (id)
                    {
                        case 1:
                            {
                                p_signature = global::Omnius.Core.Cryptography.OmniSignature.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 2:
                            {
                                p_contentHash = global::Omnius.Core.Cryptography.OmniHash.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 3:
                            {
                                p_creationTime = r.GetTimestamp();
                                break;
                            }
                    }
                }

                return new global::Omnius.Xeus.Interactors.Internal.Models.DownloadingUserProfileItem(p_signature, p_contentHash, p_creationTime);
            }
        }
    }
    public sealed partial class UploadingUserProfileItem : global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem>
    {
        public static global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem> Formatter => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem>.Formatter;
        public static global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem Empty => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem>.Empty;

        static UploadingUserProfileItem()
        {
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem>.Formatter = new ___CustomFormatter();
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem>.Empty = new global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem(global::Omnius.Core.Cryptography.OmniSignature.Empty, global::Omnius.Core.Cryptography.OmniHash.Empty, global::Omnius.Core.RocketPack.Timestamp.Zero);
        }

        private readonly global::System.Lazy<int> ___hashCode;

        public UploadingUserProfileItem(global::Omnius.Core.Cryptography.OmniSignature signature, global::Omnius.Core.Cryptography.OmniHash contentHash, global::Omnius.Core.RocketPack.Timestamp creationTime)
        {
            if (signature is null) throw new global::System.ArgumentNullException("signature");
            this.Signature = signature;
            this.ContentHash = contentHash;
            this.CreationTime = creationTime;

            ___hashCode = new global::System.Lazy<int>(() =>
            {
                var ___h = new global::System.HashCode();
                if (signature != default) ___h.Add(signature.GetHashCode());
                if (contentHash != default) ___h.Add(contentHash.GetHashCode());
                if (creationTime != default) ___h.Add(creationTime.GetHashCode());
                return ___h.ToHashCode();
            });
        }

        public global::Omnius.Core.Cryptography.OmniSignature Signature { get; }
        public global::Omnius.Core.Cryptography.OmniHash ContentHash { get; }
        public global::Omnius.Core.RocketPack.Timestamp CreationTime { get; }

        public static global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem Import(global::System.Buffers.ReadOnlySequence<byte> sequence, global::Omnius.Core.IBytesPool bytesPool)
        {
            var reader = new global::Omnius.Core.RocketPack.RocketPackObjectReader(sequence, bytesPool);
            return Formatter.Deserialize(ref reader, 0);
        }
        public void Export(global::System.Buffers.IBufferWriter<byte> bufferWriter, global::Omnius.Core.IBytesPool bytesPool)
        {
            var writer = new global::Omnius.Core.RocketPack.RocketPackObjectWriter(bufferWriter, bytesPool);
            Formatter.Serialize(ref writer, this, 0);
        }

        public static bool operator ==(global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem? left, global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem? right)
        {
            return (right is null) ? (left is null) : right.Equals(left);
        }
        public static bool operator !=(global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem? left, global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem? right)
        {
            return !(left == right);
        }
        public override bool Equals(object? other)
        {
            if (other is not global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem) return false;
            return this.Equals((global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem)other);
        }
        public bool Equals(global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem? target)
        {
            if (target is null) return false;
            if (object.ReferenceEquals(this, target)) return true;
            if (this.Signature != target.Signature) return false;
            if (this.ContentHash != target.ContentHash) return false;
            if (this.CreationTime != target.CreationTime) return false;

            return true;
        }
        public override int GetHashCode() => ___hashCode.Value;

        private sealed class ___CustomFormatter : global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem>
        {
            public void Serialize(ref global::Omnius.Core.RocketPack.RocketPackObjectWriter w, in global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem value, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                if (value.Signature != global::Omnius.Core.Cryptography.OmniSignature.Empty)
                {
                    w.Write((uint)1);
                    global::Omnius.Core.Cryptography.OmniSignature.Formatter.Serialize(ref w, value.Signature, rank + 1);
                }
                if (value.ContentHash != global::Omnius.Core.Cryptography.OmniHash.Empty)
                {
                    w.Write((uint)2);
                    global::Omnius.Core.Cryptography.OmniHash.Formatter.Serialize(ref w, value.ContentHash, rank + 1);
                }
                if (value.CreationTime != global::Omnius.Core.RocketPack.Timestamp.Zero)
                {
                    w.Write((uint)3);
                    w.Write(value.CreationTime);
                }
                w.Write((uint)0);
            }
            public global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem Deserialize(ref global::Omnius.Core.RocketPack.RocketPackObjectReader r, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                global::Omnius.Core.Cryptography.OmniSignature p_signature = global::Omnius.Core.Cryptography.OmniSignature.Empty;
                global::Omnius.Core.Cryptography.OmniHash p_contentHash = global::Omnius.Core.Cryptography.OmniHash.Empty;
                global::Omnius.Core.RocketPack.Timestamp p_creationTime = global::Omnius.Core.RocketPack.Timestamp.Zero;

                for (; ; )
                {
                    uint id = r.GetUInt32();
                    if (id == 0) break;
                    switch (id)
                    {
                        case 1:
                            {
                                p_signature = global::Omnius.Core.Cryptography.OmniSignature.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 2:
                            {
                                p_contentHash = global::Omnius.Core.Cryptography.OmniHash.Formatter.Deserialize(ref r, rank + 1);
                                break;
                            }
                        case 3:
                            {
                                p_creationTime = r.GetTimestamp();
                                break;
                            }
                    }
                }

                return new global::Omnius.Xeus.Interactors.Internal.Models.UploadingUserProfileItem(p_signature, p_contentHash, p_creationTime);
            }
        }
    }
}
