// <auto-generated/>
#nullable enable
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Omnius.Xeus.Ui.Desktop.Configuration
{
    public sealed partial class UiState : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;

        private void RaisePropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private double _fileSearchControl_TreeViewWidth;

        public double FileSearchControl_TreeViewWidth
        {
            get => _fileSearchControl_TreeViewWidth;
            set
            {
                if (!_fileSearchControl_TreeViewWidth.Equals(value))
                {
                    _fileSearchControl_TreeViewWidth = value;
                    this.RaisePropertyChanged(nameof(FileSearchControl_TreeViewWidth));
                }
            }
        }
        private bool _mainWindowModel_SelectedTabState_Status;

        public bool MainWindowModel_SelectedTabState_Status
        {
            get => _mainWindowModel_SelectedTabState_Status;
            set
            {
                if (!_mainWindowModel_SelectedTabState_Status.Equals(value))
                {
                    _mainWindowModel_SelectedTabState_Status = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTabState_Status));
                }
            }
        }
        private bool _mainWindowModel_SelectedTabState_Peers;

        public bool MainWindowModel_SelectedTabState_Peers
        {
            get => _mainWindowModel_SelectedTabState_Peers;
            set
            {
                if (!_mainWindowModel_SelectedTabState_Peers.Equals(value))
                {
                    _mainWindowModel_SelectedTabState_Peers = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTabState_Peers));
                }
            }
        }
        private bool _mainWindowModel_SelectedTabState_Search;

        public bool MainWindowModel_SelectedTabState_Search
        {
            get => _mainWindowModel_SelectedTabState_Search;
            set
            {
                if (!_mainWindowModel_SelectedTabState_Search.Equals(value))
                {
                    _mainWindowModel_SelectedTabState_Search = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTabState_Search));
                }
            }
        }
        private bool _mainWindowModel_SelectedTabState_Download;

        public bool MainWindowModel_SelectedTabState_Download
        {
            get => _mainWindowModel_SelectedTabState_Download;
            set
            {
                if (!_mainWindowModel_SelectedTabState_Download.Equals(value))
                {
                    _mainWindowModel_SelectedTabState_Download = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTabState_Download));
                }
            }
        }
        private bool _mainWindowModel_SelectedTabState_Upload;

        public bool MainWindowModel_SelectedTabState_Upload
        {
            get => _mainWindowModel_SelectedTabState_Upload;
            set
            {
                if (!_mainWindowModel_SelectedTabState_Upload.Equals(value))
                {
                    _mainWindowModel_SelectedTabState_Upload = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTabState_Upload));
                }
            }
        }
        private bool _mainWindowModel_SelectedTabState_Settings;

        public bool MainWindowModel_SelectedTabState_Settings
        {
            get => _mainWindowModel_SelectedTabState_Settings;
            set
            {
                if (!_mainWindowModel_SelectedTabState_Settings.Equals(value))
                {
                    _mainWindowModel_SelectedTabState_Settings = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTabState_Settings));
                }
            }
        }
    }
}
