@startuml

skinparam rectangle<<behavior>> {
	roundCorner 25
}
sprite $component jar:archimate/component

package Omnius.Xeus.Ui.Desktop {
    package Omnius.Xeus.Ui.Desktop.Presenters {
        rectangle UserProfileFinder <<$component>><<behavior>>
        rectangle UserProfileUploader <<$component>><<behavior>>
        rectangle FileFinder <<$component>><<behavior>>
        rectangle FileDowndoader <<$component>><<behavior>>
        rectangle FileUploader <<$component>><<behavior>>
    }
}

package Omnius.Xeus.Intaractors {
    rectangle FilePublisher <<$component>><<behavior>>
    rectangle FileSubscriber <<$component>><<behavior>>
    rectangle UserProfilePublisher <<$component>><<behavior>>
    rectangle UserProfileSubscriber <<$component>><<behavior>>
}

package Omnius.Xeus.Service.Daemon {
    rectangle XeusService.Client <<$component>><<behavior>>
    rectangle XeusService.Server <<$component>><<behavior>>
}

package Omnius.Xeus.Service.Daemon {
    rectangle XeusServiceImpl <<$component>><<behavior>>
}

package Ominus.Xeus.Engines {
    package Ominus.Xeus.Engines.Connectors {
        rectangle TcpConnector <<$component>><<behavior>>
    }
    package Ominus.Xeus.Engines.Exchangers {
        rectangle ContentExchanger <<$component>><<behavior>>
        rectangle DeclaredMessageExchanger <<$component>><<behavior>>
    }
    package Ominus.Xeus.Engines.Mediators {
        rectangle CkadMediator <<$component>><<behavior>>
    }
    package Ominus.Xeus.Engines.Storages {
        rectangle PublishedFileStorage <<$component>><<behavior>>
        rectangle SubscribedFileStorage <<$component>><<behavior>>
        rectangle PublishedDeclaredMessage <<$component>><<behavior>>
        rectangle SubscribedDeclaredMessage <<$component>><<behavior>>
    }
}

UserProfileFinder -down-> UserProfileSubscriber
UserProfileUploader -down-> UserProfilePublisher
FileFinder -down-> UserProfileFinder
FileDowndoader -down-> FileSubscriber
FileUploader -down-> FilePublisher

FilePublisher -down-> XeusService.Client
FileSubscriber -down-> XeusService.Client
UserProfilePublisher -down-> XeusService.Client
UserProfileSubscriber -down-> XeusService.Client

XeusService.Client .down.> XeusService.Server : TCP

XeusService.Server -down-> XeusServiceImpl

XeusServiceImpl -down-> Ominus.Xeus.Engines

CkadMediator -left-> TcpConnector

ContentExchanger -up-> TcpConnector
ContentExchanger -up-> CkadMediator
ContentExchanger -down-> PublishedFileStorage
ContentExchanger -down-> SubscribedFileStorage

DeclaredMessageExchanger -up-> TcpConnector
DeclaredMessageExchanger -up-> CkadMediator
DeclaredMessageExchanger -down-> PublishedDeclaredMessage
DeclaredMessageExchanger -down-> SubscribedDeclaredMessage

@enduml
