// <auto-generated/>
#nullable enable

namespace Omnius.Xeus.Interactors.Models
{
    public sealed partial class FileStorageServiceOptions : global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions>
    {
        public static global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions> Formatter => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions>.Formatter;
        public static global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions Empty => global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions>.Empty;

        static FileStorageServiceOptions()
        {
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions>.Formatter = new ___CustomFormatter();
            global::Omnius.Core.RocketPack.IRocketPackObject<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions>.Empty = new global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions();
        }

        private readonly global::System.Lazy<int> ___hashCode;

        public FileStorageServiceOptions()
        {

            ___hashCode = new global::System.Lazy<int>(() =>
            {
                var ___h = new global::System.HashCode();
                return ___h.ToHashCode();
            });
        }


        public static global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions Import(global::System.Buffers.ReadOnlySequence<byte> sequence, global::Omnius.Core.IBytesPool bytesPool)
        {
            var reader = new global::Omnius.Core.RocketPack.RocketPackObjectReader(sequence, bytesPool);
            return Formatter.Deserialize(ref reader, 0);
        }
        public void Export(global::System.Buffers.IBufferWriter<byte> bufferWriter, global::Omnius.Core.IBytesPool bytesPool)
        {
            var writer = new global::Omnius.Core.RocketPack.RocketPackObjectWriter(bufferWriter, bytesPool);
            Formatter.Serialize(ref writer, this, 0);
        }

        public static bool operator ==(global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions? left, global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions? right)
        {
            return (right is null) ? (left is null) : right.Equals(left);
        }
        public static bool operator !=(global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions? left, global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions? right)
        {
            return !(left == right);
        }
        public override bool Equals(object? other)
        {
            if (!(other is global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions)) return false;
            return this.Equals((global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions)other);
        }
        public bool Equals(global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions? target)
        {
            if (target is null) return false;
            if (object.ReferenceEquals(this, target)) return true;

            return true;
        }
        public override int GetHashCode() => ___hashCode.Value;

        private sealed class ___CustomFormatter : global::Omnius.Core.RocketPack.IRocketPackObjectFormatter<global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions>
        {
            public void Serialize(ref global::Omnius.Core.RocketPack.RocketPackObjectWriter w, in global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions value, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();

                w.Write((uint)0);
            }
            public global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions Deserialize(ref global::Omnius.Core.RocketPack.RocketPackObjectReader r, in int rank)
            {
                if (rank > 256) throw new global::System.FormatException();


                for (; ; )
                {
                    uint id = r.GetUInt32();
                    if (id == 0) break;
                    switch (id)
                    {
                    }
                }

                return new global::Omnius.Xeus.Interactors.Models.FileStorageServiceOptions();
            }
        }
    }
}
