@startuml

title Service

XeusServiceManager *--> ExchangeEngine
XeusServiceManager *--> ContentsDatabase

ContentsDatabase *--> BlocksStorage
ContentsDatabase *--> ContentsInfosManager

BlocksStorage *--> BitmapManager
BlocksStorage *--> ProtectionStatusManager
BlocksStorage *--> UsingSectorsManager

ExchangeEngine *--> ConnectionCreator
ExchangeEngine *--> DownloadManager
ExchangeEngine *--> NetworkManager

ConnectionCreator *--> CatharsisManager
ConnectionCreator *--> TcpConnectionCreator
ConnectionCreator *--> I2pConnectionCreator
ConnectionCreator *--> CustomConnectionManager

@enduml
