// <auto-generated/>
#nullable enable
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace Omnius.Lxna.Ui.Desktop.Resources.Models
{
    public sealed partial class UiState : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;

        private void RaisePropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private double _fileSearchControl_TreeViewWidth;

        public double FileSearchControl_TreeViewWidth
        {
            get => _fileSearchControl_TreeViewWidth;
            set
            {
                if (!_fileSearchControl_TreeViewWidth.Equals(value))
                {
                    _fileSearchControl_TreeViewWidth = value;
                    this.RaisePropertyChanged(nameof(FileSearchControl_TreeViewWidth));
                }
            }
        }
        private bool _mainWindowModel_SelectedTab_Status;

        public bool MainWindowModel_SelectedTab_Status
        {
            get => _mainWindowModel_SelectedTab_Status;
            set
            {
                if (!_mainWindowModel_SelectedTab_Status.Equals(value))
                {
                    _mainWindowModel_SelectedTab_Status = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTab_Status));
                }
            }
        }
        private bool _mainWindowModel_SelectedTab_Peers;

        public bool MainWindowModel_SelectedTab_Peers
        {
            get => _mainWindowModel_SelectedTab_Peers;
            set
            {
                if (!_mainWindowModel_SelectedTab_Peers.Equals(value))
                {
                    _mainWindowModel_SelectedTab_Peers = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTab_Peers));
                }
            }
        }
        private bool _mainWindowModel_SelectedTab_Search;

        public bool MainWindowModel_SelectedTab_Search
        {
            get => _mainWindowModel_SelectedTab_Search;
            set
            {
                if (!_mainWindowModel_SelectedTab_Search.Equals(value))
                {
                    _mainWindowModel_SelectedTab_Search = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTab_Search));
                }
            }
        }
        private bool _mainWindowModel_SelectedTab_Download;

        public bool MainWindowModel_SelectedTab_Download
        {
            get => _mainWindowModel_SelectedTab_Download;
            set
            {
                if (!_mainWindowModel_SelectedTab_Download.Equals(value))
                {
                    _mainWindowModel_SelectedTab_Download = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTab_Download));
                }
            }
        }
        private bool _mainWindowModel_SelectedTab_Upload;

        public bool MainWindowModel_SelectedTab_Upload
        {
            get => _mainWindowModel_SelectedTab_Upload;
            set
            {
                if (!_mainWindowModel_SelectedTab_Upload.Equals(value))
                {
                    _mainWindowModel_SelectedTab_Upload = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTab_Upload));
                }
            }
        }
        private bool _mainWindowModel_SelectedTab_Settings;

        public bool MainWindowModel_SelectedTab_Settings
        {
            get => _mainWindowModel_SelectedTab_Settings;
            set
            {
                if (!_mainWindowModel_SelectedTab_Settings.Equals(value))
                {
                    _mainWindowModel_SelectedTab_Settings = value;
                    this.RaisePropertyChanged(nameof(MainWindowModel_SelectedTab_Settings));
                }
            }
        }
    }
}
